system:
  port: 8888

mysql:
  host: 39.102.79.29:3306
  username: root
  password: lm123
  db: cloud_db
  conn:
    maxidle: 50
    maxopen: 50

redis:
  addr: 39.102.79.29:6379
  db: 1
  password: 'lm123'
  poolsize: 100
  cache:
    tokenexpired: 7200 # expired time 2*60*60

log:
  prefix: 'D://go/logs/log.txt'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

jwt:
  signkey: 'index'