system:
  port: 8888

mysql:
  host: 58.87.111.253:3306
  username: cloud_user
  password: w6TIsXDPGB3azvxdu/vF
  db: lecare_cloud_db_v2
  conn:
    maxidle: 10
    maxopen: 100

redis:
  addr: 118.89.237.99:6379
  db: 15
  password: ''
  poolsize: 100
  cache:
    tokenexpired: 7200 # expired time 2*60*60

log:
  prefix: 'D://go/logs/log.txt'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

jwt:
  signkey: 'index'