system:
  port: 8888

mysql:
  host: 58.87.111.253:3308
  username: root
  password: Lejian@123
  db: lejian_hospital
  conn:
    maxidle: 10
    maxopen: 100

redis:
  addr: 118.89.237.99:6379
  db: 15
  password: ''
  poolsize: 100
  cache:
    tokenexpired: 7200 # expired time 2*60*60

log:
  prefix: '/opt/log.txt'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

jwt:
  signKey: 'index'
  expires: 3600